### ISSUE TITLE
Важный баг который ломает весь режим

### ISSUE THREAD

**Issue by magmen3** [Deka4ka/HLC-Modded#1]
Разработчик дека, это нужно исправить
![hariri](https://github.com/Deka4ka/HLC-Modded/assets/78595463/1318389b-b32e-4101-8d0d-a5850520928a)

**Comment by Deka4ka** [comment]
Ля ты......

**Comment by Deka4ka** [comment]
Ля ты......

**Comment by magmen3** [comment]
Спасибо разрабу за то что пофиксил!!1
